# Generated by Django 3.2.19 on 2023-07-18 10:36

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmrsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('priority', models.SmallIntegerField(db_column='Priority', default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TblJrolepermission',
            fields=[
                ('rolepermissionid', models.AutoField(db_column='RolePermissionID', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Role_Permission',
                'verbose_name_plural': 'Role_Permissions',
                'db_table': 'tbl_JRolePermission',
            },
        ),
        migrations.CreateModel(
            name='TblJuserrole',
            fields=[
                ('userroleid', models.AutoField(db_column='UserRoleID', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'User_Role',
                'verbose_name_plural': 'User_Roles',
                'db_table': 'tbl_JUserRole',
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('userid', models.IntegerField(db_column='UserID', primary_key=True, serialize=False)),
                ('user', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='User', max_length=50, unique=True)),
                ('passphrase', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PassPhrase', max_length=100)),
                ('active', models.BooleanField(db_column='Active')),
                ('priority', models.SmallIntegerField(db_column='Priority')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'tbl_User',
            },
        ),
        migrations.CreateModel(
            name='TblUserlogin',
            fields=[
                ('loginid', models.AutoField(db_column='LoginID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='UserID')),
                ('enterdate', models.DateTimeField(db_column='EnterDate')),
                ('exitdate', models.DateTimeField(blank=True, db_column='ExitDate', null=True)),
            ],
            options={
                'db_table': 'tbl_UserLogin',
            },
        ),
        migrations.CreateModel(
            name='TblRole',
            fields=[
                ('roleid', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('role', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Role', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=50, null=True)),
                ('user', models.ManyToManyField(through='accounts.TblJuserrole', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'tbl_Role',
            },
        ),
        migrations.CreateModel(
            name='TblPermission',
            fields=[
                ('permissionid', models.AutoField(db_column='PermissionID', primary_key=True, serialize=False)),
                ('permission', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Permission', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=50, null=True)),
                ('role', models.ManyToManyField(through='accounts.TblJrolepermission', to='accounts.TblRole')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'tbl_Permission',
            },
        ),
        migrations.AddField(
            model_name='tbljuserrole',
            name='roleid',
            field=models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.PROTECT, related_name='Role_UserRole', to='accounts.tblrole'),
        ),
        migrations.AddField(
            model_name='tbljuserrole',
            name='userid',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, related_name='User_UserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tbljrolepermission',
            name='permissionid',
            field=models.ForeignKey(db_column='PermissionID', on_delete=django.db.models.deletion.PROTECT, related_name='Permission_RolePermission', to='accounts.tblpermission'),
        ),
        migrations.AddField(
            model_name='tbljrolepermission',
            name='roleid',
            field=models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.PROTECT, related_name='Role_RolePermission', to='accounts.tblrole'),
        ),
    ]
