# Generated by Django 3.2.19 on 2023-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmrsuser',
            name='user_img',
            field=models.ImageField(null=True, upload_to='user_images'),
        ),
    ]
