# Generated by Django 3.2.19 on 2023-08-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20230809_1657'),
        ('accounts', '0002_pmrsuser_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmrsuser',
            name='all_projects_r',
            field=models.BooleanField(db_column='AllProjectRead', default=False, null=True),
        ),
        migrations.AddField(
            model_name='pmrsuser',
            name='all_projects_w',
            field=models.BooleanField(db_column='AllProjectWrite', default=False, null=True),
        ),
        migrations.AddField(
            model_name='tbljuserrole',
            name='contractuserid',
            field=models.ForeignKey(db_column='UserContractID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UserContract_UserRole', to='contracts.tbljcontractuser'),
        ),
    ]
