# Generated by Django 3.2.19 on 2023-08-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20230809_1657'),
        ('accounts', '0003_auto_20230809_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbljuserrole',
            name='contractuserid',
        ),
        migrations.AddField(
            model_name='tbljuserrole',
            name='contractid',
            field=models.ForeignKey(db_column='ContractID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contract_UserRole', to='contracts.tblcontract'),
        ),
    ]
