# Generated by Django 3.2.19 on 2023-08-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230811_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmrsuser',
            old_name='all_projects_w',
            new_name='all_projects_rw',
        ),
    ]
