# Generated by Django 3.2.19 on 2023-08-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_tbljuserrole_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmrsuser',
            name='all_projects_r',
        ),
        migrations.RemoveField(
            model_name='pmrsuser',
            name='all_projects_rw',
        ),
        migrations.AddField(
            model_name='tbljuserrole',
            name='all_projects',
            field=models.BooleanField(db_column='AllProjects', default=False, null=True),
        ),
    ]
