# Generated by Django 3.2.19 on 2023-09-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230926_0736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblRole',
            new_name='Role',
        ),
    ]
