# Generated by Django 3.2.19 on 2023-09-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_tblrole_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblPermission',
            new_name='Permission',
        ),
    ]
