# Generated by Django 3.2.19 on 2023-09-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('accounts', '0010_rename_tblpermission_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblJrolepermission',
            new_name='RolePermission',
        ),
        migrations.RenameModel(
            old_name='TblJuserrole',
            new_name='UserRole',
        ),
    ]
