# Generated by Django 3.2.19 on 2023-08-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20230809_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblJcontractreportdate',
        ),
    ]
