# Generated by Django 3.2.19 on 2023-08-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_delete_tbljcontractreportdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcorporation',
            name='companyid',
            field=models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='Contract_Company', to='contracts.tblcompany'),
        ),
        migrations.AlterField(
            model_name='tblcorporation',
            name='contractid',
            field=models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.CASCADE, related_name='Contract_Corporation', to='contracts.tblcontract'),
        ),
    ]
