# Generated by Django 3.2.19 on 2023-08-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20230823_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcorporation',
            name='companyid',
            field=models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='Company_Corporation', to='contracts.tblcompany'),
        ),
    ]
