# Generated by Django 3.2.19 on 2023-08-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_tblcorporation_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblincrementalamount',
            name='incrementalamountdate',
            field=models.DateField(db_column='IncrementalAmountDate'),
        ),
    ]
