# Generated by Django 3.2.19 on 2023-08-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_tblincrementalamount_incrementalamountdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAddendum',
            fields=[
                ('addendumid', models.AutoField(db_column='AddendumID', primary_key=True, serialize=False)),
                ('addendumamount_r', models.BigIntegerField(db_column='AddendumAmount_R', null=True)),
                ('addendumamount_fc', models.IntegerField(db_column='AddendumAmount_FC', null=True)),
                ('addendumamountdate', models.DateField(db_column='AddendumAmountDate', null=True)),
                ('afteraddendumdate', models.DateField(db_column='AfterAddendumDate', null=True)),
            ],
            options={
                'verbose_name': 'Contract_Addendum',
                'verbose_name_plural': 'Contract_Addendums',
                'db_table': 'tbl_Addendum',
            },
        ),
        migrations.AddField(
            model_name='tblcontract',
            name='latitude',
            field=models.FloatField(db_column='Latitude', null=True),
        ),
        migrations.AddField(
            model_name='tblcontract',
            name='longitude',
            field=models.FloatField(db_column='Longitude', null=True),
        ),
        migrations.AddField(
            model_name='tblcontract',
            name='startdate',
            field=models.DateField(blank=True, db_column='StartDate', null=True),
        ),
        migrations.DeleteModel(
            name='TblIncrementalamount',
        ),
        migrations.AddField(
            model_name='tbladdendum',
            name='contractid',
            field=models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_Addendum', to='contracts.tblcontract'),
        ),
    ]
