# Generated by Django 3.2.19 on 2023-08-31 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20230828_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbladdendum',
            name='addendumamountdate',
            field=models.DateField(db_column='AddendumAmountDate', default=datetime.datetime(2023, 8, 31, 11, 17, 41, 121766), null=True),
        ),
    ]
