# Generated by Django 3.2.19 on 2023-08-31 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_tbladdendum_addendumamountdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbladdendum',
            name='addendumamountdate',
            field=models.DateField(db_column='AddendumAmountDate', default=django.utils.timezone.now, null=True),
        ),
    ]
