# Generated by Django 3.2.19 on 2023-08-31 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_tbladdendum_addendumamountdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbladdendum',
            name='addendumamountdate',
            field=models.DateField(db_column='AddendumAmountDate', default=datetime.date(2023, 8, 31), null=True),
        ),
    ]
