# Generated by Django 3.2.19 on 2023-09-15 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_alter_tbladdendum_addendumamountdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbladdendum',
            name='addendumamountdate',
            field=models.DateField(db_column='AddendumAmountDate', default=datetime.date(2023, 9, 16), null=True),
        ),
    ]
