# Generated by Django 3.2.19 on 2023-09-21 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_alter_tbladdendum_addendumamountdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbladdendum',
            name='addendumamountdate',
            field=models.DateField(db_column='AddendumAmountDate', default=django.utils.timezone.now, null=True),
        ),
    ]
