# Generated by Django 3.2.19 on 2023-09-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblCompanytype',
            new_name='CompanyType',
        ),
    ]
