# Generated by Django 3.2.19 on 2023-09-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_rename_tblcompanytype_companytype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblCompany',
            new_name='Company',
        ),
    ]
