# Generated by Django 3.2.19 on 2023-09-26 05:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20230926_0751'),
        ('projects_files', '0011_rename_tblwreportdox_reportdox'),
        ('projects', '0028_rename_tblwworkvolume_workvolume'),
        ('contracts', '0020_auto_20230926_0833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblContract',
            new_name='Contract',
        ),
        migrations.RenameModel(
            old_name='TblContracttype',
            new_name='ContractType',
        ),
        migrations.RenameModel(
            old_name='TblCountry',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='TblCurrency',
            new_name='Currency',
        ),
    ]
