# Generated by Django 3.2.19 on 2023-09-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_auto_20230926_0848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblAddendum',
            new_name='Addendum',
        ),
        migrations.RenameModel(
            old_name='TblJcontractconsultant',
            new_name='ContractConsultant',
        ),
        migrations.RenameModel(
            old_name='TblJcontractcontractor',
            new_name='ContractContractor',
        ),
        migrations.RenameModel(
            old_name='TblJcontractcurrencies',
            new_name='ContractCurrencies',
        ),
        migrations.RenameModel(
            old_name='TblCostcenter',
            new_name='CostCenter',
        ),
        migrations.RenameModel(
            old_name='TblDateconvertion',
            new_name='DateConversion',
        ),
    ]
