# Generated by Django 3.2.19 on 2023-09-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_auto_20230926_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblJschedulefinancialdocument',
            new_name='ScheduleFinancialDocument',
        ),
    ]
