# Generated by Django 3.2.19 on 2023-08-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20230730_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblwbudgetcost',
            name='dateid',
            field=models.ForeignKey(db_column='DateID', on_delete=django.db.models.deletion.PROTECT, related_name='ReportDate_BudgetCost', to='projects.tblwreportdate'),
        ),
    ]
