# Generated by Django 3.2.19 on 2023-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_tblwbudgetcost_dateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblwmachinary',
            name='activeno',
            field=models.IntegerField(db_column='ActiveNo', default=0),
        ),
        migrations.AlterField(
            model_name='tblwmachinary',
            name='inactiveno',
            field=models.IntegerField(db_column='InactiveNo', default=0),
        ),
    ]
