# Generated by Django 3.2.19 on 2023-08-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_delete_tbljcontractreportdate'),
        ('projects', '0004_auto_20230807_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblJcontractreportdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_ContractReportDate', to='contracts.tblcontract')),
                ('dateid', models.ForeignKey(db_column='DateID', on_delete=django.db.models.deletion.PROTECT, related_name='ReportDate_ContractReportDate', to='projects.tblwreportdate')),
            ],
            options={
                'verbose_name': 'Contract_ReportDate',
                'verbose_name_plural': 'Contract_ReportDates',
                'db_table': 'tbl_JContractReportDate',
            },
        ),
    ]
