# Generated by Django 3.2.19 on 2023-09-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_tblwreportdox_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblwhse',
            old_name='disadnantageeventno',
            new_name='disadvantageeventno',
        ),
    ]
