# Generated by Django 3.2.19 on 2023-09-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_disadnantageeventno_tblwhse_disadvantageeventno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblwinvoicedox',
            name='contractid',
        ),
        migrations.RemoveField(
            model_name='tblwinvoicedox',
            name='dateid',
        ),
        migrations.RemoveField(
            model_name='tblwreportdox',
            name='contractid',
        ),
        migrations.RemoveField(
            model_name='tblwreportdox',
            name='dateid',
        ),
        migrations.RemoveField(
            model_name='tblwzone',
            name='contractid',
        ),
        migrations.RemoveField(
            model_name='tblwzoneimage',
            name='dateid',
        ),
        migrations.RemoveField(
            model_name='tblwzoneimage',
            name='zoneid',
        ),
        migrations.DeleteModel(
            name='TblwContractdox',
        ),
        migrations.DeleteModel(
            name='TblwInvoicedox',
        ),
        migrations.DeleteModel(
            name='TblwReportdox',
        ),
        migrations.DeleteModel(
            name='TblwZone',
        ),
        migrations.DeleteModel(
            name='TblwZoneimage',
        ),
    ]
