# Generated by Django 3.2.19 on 2023-09-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects', '0010_auto_20230926_0640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwBudgetcost',
            new_name='Budgetcost',
        ),
    ]
