# Generated by Django 3.2.19 on 2023-09-26 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_files', '0009_tblwcontractdox_tblwinvoicedox_tblwreportdox_tblwzone_tblwzoneimage'),
        ('projects', '0011_rename_tblwbudgetcost_budgetcost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwReportdate',
            new_name='Reportdate',
        ),
    ]
