# Generated by Django 3.2.19 on 2023-09-26 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects', '0012_rename_tblwreportdate_reportdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblJcontractreportdate',
            new_name='ContractReportDate',
        ),
    ]
