# Generated by Django 3.2.19 on 2023-09-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_tblwcriticalaction_criticalaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwDateconversion',
            new_name='DateConversion',
        ),
    ]
