# Generated by Django 3.2.19 on 2023-09-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects', '0015_rename_tblwdateconversion_dateconversion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwFinancialinfo',
            new_name='FinancialInfo',
        ),
    ]
