# Generated by Django 3.2.19 on 2023-09-26 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects', '0020_rename_tblwmachinary_machinary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwPmsprogress',
            new_name='PmsProgress',
        ),
    ]
