# Generated by Django 3.2.19 on 2023-09-26 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects', '0021_rename_tblwpmsprogress_pmsprogress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwProblem',
            new_name='Problem',
        ),
    ]
