# Generated by Django 3.2.19 on 2023-09-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects', '0022_rename_tblwproblem_problem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwProgressstate',
            new_name='ProgressState',
        ),
    ]
