# Generated by Django 3.2.19 on 2023-09-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects', '0023_rename_tblwprogressstate_progressstate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwProjectpersonel',
            new_name='ProjectPersonnel',
        ),
    ]
