# Generated by Django 3.2.19 on 2023-09-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects', '0026_auto_20230926_0725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwTimeprogressstate',
            new_name='TimeprogressState',
        ),
        migrations.AlterUniqueTogether(
            name='reportvisit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reportvisit',
            name='contractid',
        ),
        migrations.RemoveField(
            model_name='reportvisit',
            name='dateid',
        ),
        migrations.DeleteModel(
            name='ReportVisitdate',
        ),
        migrations.DeleteModel(
            name='ReportVisit',
        ),
    ]
