# Generated by Django 3.2.19 on 2023-09-15 20:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_files', '0002_alter_hsereportdox_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsereportdox',
            name='file',
            field=models.FileField(db_column='File', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Hse_Reports'), upload_to=''),
        ),
    ]
