# Generated by Django 3.2.19 on 2023-09-25 19:12

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_disadnantageeventno_tblwhse_disadvantageeventno'),
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects_files', '0006_alter_hsereportdox_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMonthlyDox',
            fields=[
                ('projectmonthlydoxid', models.AutoField(db_column='ProjectMonthlyDoxId', primary_key=True, serialize=False)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=250)),
                ('file', models.FileField(db_column='File', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Project Monthly Reports'), unique=True, upload_to='')),
                ('active', models.BooleanField(blank=True, db_column='Active', null=True)),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_ProjectMonthlyDox', to='contracts.tblcontract')),
                ('dateid', models.ForeignKey(db_column='DateID', on_delete=django.db.models.deletion.PROTECT, related_name='ReportDate_ProjectMonthlyDox', to='projects.tblwreportdate')),
            ],
            options={
                'db_table': 'tblw_ProjectMonthlyDox',
            },
        ),
        migrations.CreateModel(
            name='ProjectDox',
            fields=[
                ('projectdoxid', models.AutoField(db_column='ProjectDoxID', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', default=django.utils.timezone.now, null=True)),
                ('doctitle', models.PositiveSmallIntegerField(db_column='DocTitle', null=True)),
                ('dockind', models.PositiveSmallIntegerField(db_column='DocKind', null=True)),
                ('docno', models.PositiveSmallIntegerField(db_column='DocNo', null=True)),
                ('file', models.FileField(db_column='File', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Project Contract'), unique=True, upload_to='')),
                ('active', models.BooleanField(blank=True, db_column='Active', null=True)),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_ProjectDox', to='contracts.tblcontract')),
                ('dateid', models.ForeignKey(db_column='DateID', on_delete=django.db.models.deletion.PROTECT, related_name='ReportDate_ProjectDox', to='projects.tblwreportdate')),
            ],
            options={
                'db_table': 'tblw_ProjectDox',
            },
        ),
        migrations.CreateModel(
            name='ContractorDox',
            fields=[
                ('contractordoxid', models.AutoField(db_column='ContractorDoxId', primary_key=True, serialize=False)),
                ('contractdate', models.DateField(blank=True, db_column='ContractDate', default=django.utils.timezone.now, null=True)),
                ('contracttitle', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContractTitle', max_length=250)),
                ('contractor', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contractor', max_length=250)),
                ('contractNo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContractNo', max_length=50)),
                ('riderno', models.PositiveSmallIntegerField(db_column='RiderNo')),
                ('file', models.FileField(db_column='File', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Project Sub Contracts'), unique=True, upload_to='')),
                ('active', models.BooleanField(blank=True, db_column='Active', null=True)),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_ContractorDox', to='contracts.tblcontract')),
                ('dateid', models.ForeignKey(db_column='DateID', on_delete=django.db.models.deletion.PROTECT, related_name='ReportDate_ContractorDox', to='projects.tblwreportdate')),
            ],
            options={
                'db_table': 'tblw_ContractorDox',
            },
        ),
        migrations.CreateModel(
            name='ApprovedInvoiceDox',
            fields=[
                ('approvedinvoicedoxid', models.AutoField(db_column='ApprovedInvoiceDoxId', primary_key=True, serialize=False)),
                ('invoiceKind', models.PositiveSmallIntegerField(db_column='InvoiceKind')),
                ('invoiceNo', models.PositiveSmallIntegerField(db_column='InvoiceNo')),
                ('invoiceDate', models.DateField(db_column='InvoiceDate')),
                ('sendDate', models.DateField(db_column='SendDate', null=True)),
                ('confirmDate', models.DateField(db_column='ConfirmDate', null=True)),
                ('sgp_r', models.IntegerField(db_column='SGP_R', null=True)),
                ('sgp_fc', models.BigIntegerField(db_column='SGP_FC', null=True)),
                ('cgp_r', models.IntegerField(db_column='CGP_R', null=True)),
                ('cgp_fc', models.BigIntegerField(db_column='CGP_FC', null=True)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=250, null=True)),
                ('file', models.FileField(db_column='File', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Approved Invoices'), unique=True, upload_to='')),
                ('active', models.BooleanField(blank=True, db_column='Active', null=True)),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_ApprovedInvoiceDox', to='contracts.tblcontract')),
                ('dateid', models.ForeignKey(db_column='DateID', on_delete=django.db.models.deletion.PROTECT, related_name='ReportDate_ApprovedInvoiceDox', to='projects.tblwreportdate')),
            ],
            options={
                'db_table': 'tblw_ApprovedInvoiceDox',
            },
        ),
    ]
