# Generated by Django 3.2.19 on 2023-09-26 03:10

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects', '0010_auto_20230926_0640'),
        ('projects_files', '0008_auto_20230925_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblwZone',
            fields=[
                ('zoneid', models.AutoField(db_column='ZoneID', primary_key=True, serialize=False)),
                ('zone', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Zone', max_length=50)),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_Zone', to='contracts.tblcontract')),
            ],
            options={
                'db_table': 'tblw_Zone',
            },
        ),
        migrations.CreateModel(
            name='TblwZoneimage',
            fields=[
                ('zoneimageid', models.AutoField(db_column='ZoneImageID', primary_key=True, serialize=False)),
                ('ppp', models.DecimalField(blank=True, db_column='PPP', decimal_places=2, max_digits=6, null=True)),
                ('app', models.DecimalField(blank=True, db_column='APP', decimal_places=2, max_digits=6, null=True)),
                ('pic1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pic1', max_length=250, null=True)),
                ('description1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description1', max_length=250, null=True)),
                ('pic2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pic2', max_length=250, null=True)),
                ('description2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description2', max_length=250, null=True)),
                ('pic3', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pic3', max_length=250, null=True)),
                ('description3', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description3', max_length=250, null=True)),
                ('dateid', models.ForeignKey(db_column='DateID', on_delete=django.db.models.deletion.PROTECT, related_name='ReportDate', to='projects.tblwreportdate')),
                ('zoneid', models.ForeignKey(db_column='ZoneID', on_delete=django.db.models.deletion.DO_NOTHING, to='projects_files.tblwzone')),
            ],
            options={
                'db_table': 'tblw_ZoneImage',
            },
        ),
        migrations.CreateModel(
            name='TblwReportdox',
            fields=[
                ('reportdoxid', models.AutoField(db_column='ReportDoxID', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('doctype', models.SmallIntegerField(db_column='DocType')),
                ('doctitle', models.SmallIntegerField(blank=True, db_column='DocTitle', null=True)),
                ('dockind', models.SmallIntegerField(blank=True, db_column='DocKind', null=True)),
                ('docno', models.IntegerField(blank=True, db_column='DocNo', null=True)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=250)),
                ('file', models.FileField(db_column='File', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:/projects/cost_control/files/projectsDox/hseDox'), upload_to='')),
                ('address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Address', max_length=250)),
                ('active', models.BooleanField(blank=True, db_column='Active', null=True)),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_ReportDox', to='contracts.tblcontract')),
                ('dateid', models.ForeignKey(db_column='DateID', on_delete=django.db.models.deletion.PROTECT, related_name='ReportDate_ReportDox', to='projects.tblwreportdate')),
            ],
            options={
                'db_table': 'tblw_ReportDox',
            },
        ),
        migrations.CreateModel(
            name='TblwInvoicedox',
            fields=[
                ('invoicedoxid', models.AutoField(db_column='InvoiceDoxID', primary_key=True, serialize=False)),
                ('invoicekind', models.SmallIntegerField(db_column='InvoiceKind')),
                ('invoiceno', models.IntegerField(db_column='InvoiceNo')),
                ('invoicedate', models.DateField(db_column='InvoiceDate')),
                ('senddate', models.DateField(blank=True, db_column='SendDate', null=True)),
                ('confirmdate', models.DateField(blank=True, db_column='ConfirmDate', null=True)),
                ('sgp_r', models.IntegerField(blank=True, db_column='SGP_R', null=True)),
                ('sgp_fc', models.BigIntegerField(blank=True, db_column='SGP_FC', null=True)),
                ('cgp_r', models.IntegerField(blank=True, db_column='CGP_R', null=True)),
                ('cgp_fc', models.BigIntegerField(blank=True, db_column='CGP_FC', null=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=250, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Address', max_length=250, null=True)),
                ('active', models.BooleanField(db_column='Active')),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_Invoicedox', to='contracts.tblcontract')),
                ('dateid', models.ForeignKey(db_column='DateID', on_delete=django.db.models.deletion.PROTECT, related_name='ReportDate_Invoicedox', to='projects.tblwreportdate')),
            ],
            options={
                'db_table': 'tblw_InvoiceDox',
            },
        ),
        migrations.CreateModel(
            name='TblwContractdox',
            fields=[
                ('contractdoxid', models.AutoField(db_column='ContractDoxID', primary_key=True, serialize=False)),
                ('contracttitle', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContractTitle', max_length=250)),
                ('contractor', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contractor', max_length=250)),
                ('contractdate', models.DateField(blank=True, db_column='ContractDate', null=True)),
                ('contractno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContractNo', max_length=50, null=True)),
                ('riderno', models.SmallIntegerField(blank=True, db_column='RiderNo', null=True)),
                ('fileaddress', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FileAddress', max_length=250)),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_ContractDox', to='contracts.tblcontract')),
            ],
            options={
                'db_table': 'tblw_ContractDox',
            },
        ),
    ]
