# Generated by Django 3.2.19 on 2023-09-26 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects', '0027_auto_20230926_0732'),
        ('projects_files', '0009_tblwcontractdox_tblwinvoicedox_tblwreportdox_tblwzone_tblwzoneimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVisitdate',
            fields=[
                ('visitreportdateid', models.AutoField(db_column='VisitReportDateID', primary_key=True, serialize=False)),
                ('visitreportid', models.IntegerField(db_column='VisitReportID')),
                ('reportid', models.IntegerField(db_column='ReportID')),
                ('reportvisitdate', models.DateField(db_column='ReportVisitDate')),
            ],
            options={
                'db_table': 'tblw_ReportVisitDate',
            },
        ),
        migrations.CreateModel(
            name='ReportVisit',
            fields=[
                ('reportvisitid', models.AutoField(db_column='ReportVisitID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='UserID')),
                ('financialinfo', models.BooleanField(db_column='FinancialInfo')),
                ('hse', models.BooleanField(db_column='HSE')),
                ('progressstate', models.BooleanField(db_column='ProgressState')),
                ('timeprogressstate', models.BooleanField(db_column='TimeProgressState')),
                ('invoice', models.BooleanField(db_column='Invoice')),
                ('financialinvoice', models.BooleanField(db_column='FinancialInvoice')),
                ('workvolume', models.BooleanField(db_column='WorkVolume')),
                ('pmsprogress', models.BooleanField(db_column='PMSProgress')),
                ('budget', models.BooleanField(db_column='Budget')),
                ('machinary', models.BooleanField(db_column='Machinary')),
                ('personel', models.BooleanField(db_column='Personel')),
                ('problems', models.BooleanField(db_column='Problems')),
                ('criticalactions', models.BooleanField(db_column='CriticalActions')),
                ('zoneimages', models.BooleanField(db_column='ZoneImages')),
                ('projectdox', models.BooleanField(db_column='ProjectDox')),
                ('durationdox', models.BooleanField(db_column='DurationDox')),
                ('dashboard_r', models.BooleanField(db_column='Dashboard_R')),
                ('dashboard_fc', models.BooleanField(db_column='Dashboard_FC')),
                ('imagereport', models.BooleanField(db_column='ImageReport')),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_ReportVisit', to='contracts.tblcontract')),
                ('dateid', models.ForeignKey(db_column='DateID', on_delete=django.db.models.deletion.PROTECT, related_name='ReportDate_ReportVisit', to='projects.reportdate')),
            ],
            options={
                'db_table': 'tblw_ReportVisit',
                'unique_together': {('userid', 'contractid', 'dateid')},
            },
        ),
    ]
