# Generated by Django 3.2.19 on 2023-09-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_rename_tblwworkvolume_workvolume'),
        ('contracts', '0017_alter_tbladdendum_addendumamountdate'),
        ('projects_files', '0010_reportvisit_reportvisitdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwReportdox',
            new_name='ReportDox',
        ),
    ]
