# Generated by Django 3.2.19 on 2023-09-26 10:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_rename_tbljschedulefinancialdocument_schedulefinancialdocument'),
        ('projects', '0028_rename_tblwworkvolume_workvolume'),
        ('projects_files', '0011_rename_tblwreportdox_reportdox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwZone',
            new_name='Zone',
        ),
        migrations.RenameModel(
            old_name='TblwZoneimage',
            new_name='Zoneimage',
        ),
        migrations.AddField(
            model_name='tblwcontractdox',
            name='file',
            field=models.FileField(db_column='File', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Project Sub Contracts'), unique=True, upload_to=''),
        ),
    ]
