# Generated by Django 3.2.19 on 2023-09-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_rename_tblwworkvolume_workvolume'),
        ('contracts', '0025_rename_tbljschedulefinancialdocument_schedulefinancialdocument'),
        ('projects_files', '0012_auto_20230926_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblwContractdox',
            new_name='ContractDox',
        ),
        migrations.RenameModel(
            old_name='TblwInvoicedox',
            new_name='Invoicedox',
        ),
    ]
