# Generated by Django 3.2.19 on 2023-09-26 19:50

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_files', '0013_auto_20230926_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneimage',
            name='img1',
            field=models.FileField(db_column='Img1', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Approved Invoices'), unique=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='zoneimage',
            name='img2',
            field=models.FileField(db_column='Img2', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Approved Invoices'), unique=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='zoneimage',
            name='img3',
            field=models.FileField(db_column='Img3', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Approved Invoices'), unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zoneimage',
            name='zoneid',
            field=models.ForeignKey(db_column='ZoneID', on_delete=django.db.models.deletion.PROTECT, related_name='Zone_Zoneimage', to='projects_files.zone'),
        ),
    ]
