# Generated by Django 3.2.19 on 2023-09-27 16:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_files', '0014_auto_20230926_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedox',
            name='file',
            field=models.FileField(db_column='File', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Approved Invoices'), unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zoneimage',
            name='img1',
            field=models.FileField(db_column='Img1', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Constructions Pix'), unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zoneimage',
            name='img2',
            field=models.FileField(db_column='Img2', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Constructions Pix'), unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zoneimage',
            name='img3',
            field=models.FileField(db_column='Img3', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Constructions Pix'), unique=True, upload_to=''),
        ),
    ]
