# Generated by Django 3.2.19 on 2023-09-30 16:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_files', '0015_auto_20230927_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoneimage',
            name='img1',
            field=models.ImageField(db_column='Img1', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Constructions Pix'), unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zoneimage',
            name='img2',
            field=models.ImageField(db_column='Img2', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Constructions Pix'), unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zoneimage',
            name='img3',
            field=models.ImageField(db_column='Img3', null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Constructions Pix'), unique=True, upload_to=''),
        ),
    ]
